# Database & Hikari Connection Pool Settings
spring:
  datasource:
    generate-unique-name: false
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000

  # JPA / Hibernate Settings
  jpa:
    generate-ddl: true
    show-sql: true
    database: default
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # Security & Keycloak (OAuth2)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/master

  # Kafka Settings
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: travel-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Custom Properties
topicName: travels

keycloak:
  issuer: http://localhost:8080/realms/master
  realm: master

# Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Swagger / OpenAPI
springdoc:
  swagger-ui:
    oauth:
      use-pkce-with-authorization-code-grant: true

# Eureka Client Settings
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: false
  instance:
    prefer-ip-address: false
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
